//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorcycleKyrs.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int O_ID { get; set; }
        public int ID_Motorcycles { get; set; }
        public int ID_Klients { get; set; }
        public System.DateTime O_Order_date { get; set; }
        public decimal O_Price { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Motorcycle Motorcycle { get; set; }
    }
}
